FROM nginxinc/nginx-unprivileged:1-alpine
LABEL maintainer="aureliandev.com"

COPY ./default.conf.tpl /etc/nginx/default.conf.tpl
COPY ./uwsgi_params /etc/ngnix/uwsgi_params
COPY ./run.sh /run.sh

ENV LISTEN_PORT=8000
ENV APP_HOST=app
ENV APP_PORT=9000

USER root

RUN mkdir -p /vol/static && \
    chmod 755 /vol/static && \
    touch /etc/nginx/conf.d/default.conf && \
    chown nginx:nginx /etc/nginx/conf.d/default.conf && \
    chmod +x /run.sh && \
    mkdir -p /run && \
    chown nginx:nginx /run && \
    chmod 755 /run

VOLUME /vol/static

USER nginx

CMD ["/run.sh"]
